[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "fugashi>=1.5.2",
    "jamdict>=0.1a11.post2",
    "jamdict-data>=1.5",
    "kokoro>=0.9.4",
    "misaki[ja]>=0.9.4",
    "soundfile>=0.14.0",
    "unidic-lite>=1.0.8",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
